#!/usr/bin/env ruby

# to be run by teachers/contributors when developing solutions
# adds 'solution' to the load path

# todo: support multiple solutions dirs

spec_file = ARGV[0]
puts "Running #{spec_file} with solution"
dirs = spec_file.split('/')
dirs.pop
dir = if dirs.empty?
  "solution"
else
  "#{dirs.join('/')}/solution"
end
$: << "./#{dir}"

require 'rubygems'
version = "1.3.0"
gem 'rspec', version
load Gem.bin_path('rspec', 'spec', version)

p Gem.path
rspec_dir = File.expand_path(File.join(File.dirname(__FILE__), '..', 'lib'))
$LOAD_PATH.unshift(rspec_dir) unless $LOAD_PATH.include?(rspec_dir)
require 'spec/autorun'
exit ::Spec::Runner::CommandLine.run
